"""
generate_scripts.py — Step 4 of the pipeline.
Reads build/<name>/scenes.json and generates one Manim scene .py per
scene block, plus a narration script (EN + Hinglish) with timestamps.

Usage:
    python pipeline/generate_scripts.py build/attention/scenes.json
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

TEMPLATE = '''"""Auto-generated by the_math_of_tech pipeline. Edit freely —
regeneration overwrites this file (customizations go in scene_library.py)."""
import sys
from pathlib import Path
sys.path.insert(0, r"{root}")

from templates.scene_library import {cls}


class {scene_name}({cls}):
    spec = {spec}
'''

CLASS_MAP = {
    "concept_title": "ConceptTitle",
    "equation_reveal": "EquationReveal",
    "equation_annotated": "EquationAnnotated",
    "equation_steps": "EquationSteps",
    "transform": "TransformExplainer",
    "graph": "GraphScene",
    "graph_morph": "GraphMorph",
    "tokens_to_vectors": "TokensToVectors",
    "neural_net": "NeuralNet",
    "attention_matrix": "AttentionMatrix",
    "matrix_multiply": "MatrixMultiply",
    "softmax_build": "SoftmaxBuild",
    "multi_head": "MultiHead",
    "table": "TableReveal",
    "bullet_points": "BulletPoints",
}


def pascal(s: str) -> str:
    return "".join(w.capitalize() for w in s.replace("-", "_").split("_"))


def main():
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    spec_path = Path(sys.argv[1])
    project = json.loads(spec_path.read_text(encoding="utf-8"))
    out_dir = spec_path.parent / "scenes"
    out_dir.mkdir(exist_ok=True)

    narration = [f"# Narration script — {project['video_title']}\n"]
    t = 0.0
    for s in project["scenes"]:
        cls = CLASS_MAP[s["type"]]
        scene_name = f"S{s['order']:02d}{pascal(s['id'])}"
        spec = {k: v for k, v in s.items()
                if k not in ("narration_en", "narration_hi", "reel", "order")}
        code = TEMPLATE.format(root=str(ROOT), cls=cls,
                               scene_name=scene_name, spec=repr(spec))
        f = out_dir / f"{s['order']:02d}_{s['id']}.py"
        f.write_text(code, encoding="utf-8")

        mm, ss = divmod(int(t), 60)
        reel_tag = " [REEL]" if s.get("reel") else ""
        narration.append(
            f"\n## [{mm:02d}:{ss:02d}] {s['id']}{reel_tag} "
            f"(~{s['duration']}s)\n"
            f"- EN: {s.get('narration_en', '(write me)')}\n"
            f"- HI: {s.get('narration_hi', '(write me)')}\n"
        )
        t += s["duration"]
        print(f"generated {f.name} -> class {scene_name}")

    (spec_path.parent / "narration.md").write_text(
        "".join(narration), encoding="utf-8")
    print(f"narration script -> {spec_path.parent / 'narration.md'}")
    print(f"total planned runtime: ~{int(t)}s")


if __name__ == "__main__":
    main()
